# Generated by Django 5.1.4 on 2025-02-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('catagory', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], max_length=10)),
            ],
        ),
    ]
